# Generated by Django 5.2.15 on 2026-08-16 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=60, unique=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('r2', models.FloatField()),
                ('mape', models.FloatField()),
                ('cv_r2_mean', models.FloatField()),
                ('cv_r2_std', models.FloatField(default=0)),
                ('train_seconds', models.FloatField()),
                ('is_best', models.BooleanField(db_index=True, default=False)),
                ('trained_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['rmse'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Set for anonymous users so their results survive a page refresh (Phase 9).', max_length=40)),
                ('location_name', models.CharField(max_length=120)),
                ('area_sqft', models.FloatField()),
                ('bhk', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('balcony', models.PositiveSmallIntegerField(default=0)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_years', models.PositiveSmallIntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('furnishing', models.CharField(default='Unfurnished', max_length=12)),
                ('property_type', models.CharField(default='Apartment', max_length=24)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence_score', models.FloatField()),
                ('model_name', models.CharField(max_length=60)),
                ('model_version', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='properties.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='predictor_p_created_198c55_idx')],
            },
        ),
    ]
