# Generated by Django 5.2.15 on 2026-08-16 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('icon_key', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tier', models.CharField(choices=[('Premium', 'Premium'), ('Mid', 'Mid'), ('Budget', 'Budget')], db_index=True, default='Mid', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_approximate', models.BooleanField(default=False, help_text='True when lat/lng fell back to the city centroid at geocode time.')),
                ('listing_count', models.PositiveIntegerField(default=0)),
                ('median_price_per_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sqft', models.FloatField()),
                ('bhk', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('balcony', models.PositiveSmallIntegerField(default=0)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_years', models.PositiveSmallIntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('furnishing', models.CharField(choices=[('Unfurnished', 'Unfurnished'), ('Semi', 'Semi'), ('Full', 'Full')], default='Unfurnished', max_length=12)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Independent House', 'Independent House'), ('Plot', 'Plot')], db_index=True, default='Apartment', max_length=24)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('listed_on', models.DateField()),
                ('source', models.CharField(choices=[('Dataset', 'Dataset'), ('Manual', 'Manual')], db_index=True, default='Dataset', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.location')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-listed_on'],
                'indexes': [models.Index(fields=['location', 'bhk'], name='properties__locatio_510c7b_idx'), models.Index(fields=['source'], name='properties__source_afbc87_idx')],
            },
        ),
    ]
